"use strict";
let myName = document.getElementById('Name');
let Desination = document.getElementById('Desination');
let Phone = document.getElementById('Phone');
let email = document.getElementById('email');
let Address = document.getElementById('Address');
let Pass = document.getElementById('Pass');
let Degree = document.getElementById('Degree');
let Uni = document.getElementById('Uni');
let Pass2 = document.getElementById('Pass2');
let Degree2 = document.getElementById('Degree2');
let Uni2 = document.getElementById('Uni2');
let skill1 = document.getElementById('skill1');
let skill2 = document.getElementById('skill2');
let skill3 = document.getElementById('skill3');
let lang1 = document.getElementById('lang1');
let lang2 = document.getElementById('lang2');
let styear = document.getElementById('styear');
let endyear = document.getElementById('endyear');
let Company = document.getElementById('Company');
let Complocation = document.getElementById('Complocation');
let jobtitle = document.getElementById('jobtitle');
let achv1 = document.getElementById('achv1');
let achv2 = document.getElementById('achv2');
let achv3 = document.getElementById('achv3');
let pic = document.getElementById('pic');
let submitbtn = document.getElementById('submitbtn');
let form = document.getElementById('form');
form?.addEventListener('submit', (e) => {
    e.preventDefault();
    localStorage.setItem('Name', myName.value);
    localStorage.setItem('Desination', Desination.value);
    localStorage.setItem('Phone', Phone.value);
    localStorage.setItem('email', email.value);
    localStorage.setItem('Address', Address.value);
    localStorage.setItem('Pass', Pass.value);
    localStorage.setItem('Degree', Degree.value);
    localStorage.setItem('Uni', Uni.value);
    localStorage.setItem('Pass2', Pass2.value);
    localStorage.setItem('Degree2', Degree2.value);
    localStorage.setItem('Uni2', Uni2.value);
    localStorage.setItem('skill1', skill1.value);
    localStorage.setItem('skill2', skill2.value);
    localStorage.setItem('skill3', skill3.value);
    localStorage.setItem('lang1', lang1.value);
    localStorage.setItem('lang2', lang2.value);
    localStorage.setItem('styear', styear.value);
    localStorage.setItem('endyear', endyear.value);
    localStorage.setItem('Company', Company.value);
    localStorage.setItem('Complocation', Complocation.value);
    localStorage.setItem('jobtitle', jobtitle.value);
    localStorage.setItem('achv1', achv1.value);
    localStorage.setItem('achv2', achv2.value);
    localStorage.setItem('achv3', achv3.value);
    if (pic.files && pic.files[0]) {
        let reader = new FileReader();
        reader.addEventListener("load", () => {
            let textimg = reader.result;
            localStorage.setItem('Profile_pic', textimg);
        });
        reader.readAsDataURL(pic.files[0]);
    }
    window.location.href = "./resume/resume.html";
});
